# Generated by Django 5.2.5 on 2025-08-18 12:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('country', models.CharField(default='Portugal', max_length=100)),
                ('building_number', models.CharField(blank=True, max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('additional_info', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
