# Generated by Django 4.2.24 on 2025-09-05 18:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('title', models.CharField(help_text='Chapter title', max_length=255)),
                ('content', models.TextField(help_text='Chapter content (text, quiz questions, etc.)')),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Quiz', 'Quiz'), ('Video', 'Video')], help_text='Type of chapter content', max_length=20)),
                ('video', models.URLField(blank=True, help_text='Video URL for video-type chapters')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this chapter within the section')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'chapters',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('teacherName', models.CharField(help_text="Teacher's name (denormalized for performance)", max_length=255)),
                ('title', models.CharField(default='Curso sem título', help_text='Course title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('category', models.CharField(default='Sem categoria', help_text='Course category', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Course thumbnail image', upload_to='courses/images/%Y/%m/')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Course price in EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', help_text='Course difficulty level', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', help_text='Course publication status', max_length=20)),
                ('teacher', models.ForeignKey(help_text='Teacher who created this course', on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('enrollmentDate', models.DateTimeField(help_text='When user enrolled in the course')),
                ('overallProgress', models.FloatField(default=0.0, help_text='Overall completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('lastAccessedTimestamp', models.DateTimeField(auto_now=True, help_text='Last time user accessed this course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Course Progress',
                'verbose_name_plural': 'User Course Progress',
                'db_table': 'user_course_progress',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('transactionId', models.CharField(help_text='External transaction ID from payment provider', max_length=255, unique=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True, help_text='Transaction timestamp')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paymentProvider', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', help_text='Payment provider used', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-dateTime'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('sectionTitle', models.CharField(help_text='Section title', max_length=255)),
                ('sectionDescription', models.TextField(blank=True, help_text='Section description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this section within the course')),
                ('course', models.ForeignKey(help_text='Course this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Course Sections',
                'db_table': 'course_sections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='When the user enrolled in the course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'db_table': 'course_enrollments',
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('completed', models.BooleanField(default=False, help_text='Whether this chapter has been completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this chapter was completed', null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.chapter')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='courses.usercourseprogress')),
            ],
            options={
                'verbose_name': 'Chapter Progress',
                'verbose_name_plural': 'Chapter Progress',
                'db_table': 'chapter_progress',
            },
        ),
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('text', models.TextField(help_text='Comment text')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter Comment',
                'verbose_name_plural': 'Chapter Comments',
                'db_table': 'chapter_comments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(help_text='Section this chapter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.coursesection'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['user'], name='user_course_user_id_8166b8_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['course'], name='user_course_course__689467_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['lastAccessedTimestamp'], name='user_course_lastAcc_d86131_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='transaction_user_id_b5bcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['course'], name='transaction_course__d6118e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['dateTime'], name='transaction_dateTim_f46b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transactionId'], name='transaction_transac_687046_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['course', 'order'], name='course_sect_course__be0a09_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user'], name='course_enro_user_id_79d5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course'], name='course_enro_course__4c96ff_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['enrollment_date'], name='course_enro_enrollm_7b95c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher'], name='courses_teacher_e891c2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_categor_33f89e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='courses_level_838724_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_status_67f368_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='courses_created_0aa93c_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterprogress',
            index=models.Index(fields=['user_progress'], name='chapter_pro_user_pr_c62bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterprogress',
            index=models.Index(fields=['chapter'], name='chapter_pro_chapter_4e0731_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterprogress',
            index=models.Index(fields=['completed'], name='chapter_pro_complet_f1f6c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapterprogress',
            unique_together={('user_progress', 'chapter')},
        ),
        migrations.AddIndex(
            model_name='chaptercomment',
            index=models.Index(fields=['chapter', '-timestamp'], name='chapter_com_chapter_832c28_idx'),
        ),
        migrations.AddIndex(
            model_name='chaptercomment',
            index=models.Index(fields=['user', '-timestamp'], name='chapter_com_user_id_73d1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['section', 'order'], name='chapters_section_6c0e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['type'], name='chapters_type_18ba47_idx'),
        ),
    ]
