# Generated by Django 4.2.24 on 2025-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_create_course_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, help_text='Course thumbnail image URL (S3 or local)'),
        ),
    ]
