# Generated by Django 4.2.24 on 2025-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='template',
            field=models.CharField(choices=[('general', 'Inglês Geral'), ('business', 'Inglês para Negócios'), ('technology', 'Inglês para Tecnologia'), ('medical', 'Inglês Médico'), ('legal', 'Inglês Jurídico')], default='general', help_text='Course template type for styling and content focus', max_length=20),
        ),
    ]
