# Generated by Django 4.2.24 on 2025-09-11 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_achievement_achievementcategory_userachievement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_add_template_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='practice_lesson',
            field=models.ForeignKey(blank=True, help_text='Connected Practice Lab lesson for gamified quizzes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice.practicelesson'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='quiz_enabled',
            field=models.BooleanField(default=False, help_text='Whether this chapter has an interactive quiz'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='resources_data',
            field=models.JSONField(default=list, help_text='Array of chapter resources (PDFs, links, etc.)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='transcript',
            field=models.TextField(blank=True, help_text='Video transcript with timestamps (JSON format)'),
        ),
        migrations.CreateModel(
            name='ChapterQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('title', models.CharField(help_text='Quiz title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Quiz description/instructions')),
                ('points_reward', models.PositiveIntegerField(default=15, help_text='Points awarded for completing quiz')),
                ('hearts_cost', models.PositiveIntegerField(default=1, help_text='Hearts lost per wrong answer')),
                ('passing_score', models.PositiveIntegerField(default=80, help_text='Minimum score percentage to pass')),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in seconds (null = no limit)', null=True)),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum attempts allowed')),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Total attempts by all students')),
                ('total_completions', models.PositiveIntegerField(default=0, help_text='Total successful completions')),
                ('average_score', models.FloatField(default=0.0, help_text='Average score across all attempts')),
                ('is_active', models.BooleanField(default=True, help_text='Whether quiz is active and available')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.chapter')),
                ('created_by', models.ForeignKey(help_text='Teacher who created this quiz', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('practice_lesson', models.ForeignKey(help_text='Connected Practice Lab lesson', on_delete=django.db.models.deletion.CASCADE, to='practice.practicelesson')),
            ],
            options={
                'verbose_name': 'Chapter Quiz',
                'verbose_name_plural': 'Chapter Quizzes',
                'db_table': 'chapter_quizzes',
            },
        ),
        migrations.CreateModel(
            name='StudentQuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('score', models.PositiveIntegerField(help_text='Score achieved')),
                ('max_score', models.PositiveIntegerField(help_text='Maximum possible score')),
                ('time_taken', models.PositiveIntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('hearts_lost', models.PositiveIntegerField(default=0, help_text='Hearts lost during this attempt')),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points earned for this attempt')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the quiz was completed')),
                ('is_passed', models.BooleanField(default=False, help_text='Whether the passing score was achieved')),
                ('attempt_number', models.PositiveIntegerField(help_text='Attempt number for this student')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the quiz was completed', null=True)),
                ('chapter_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.chapterquiz')),
                ('practice_progress', models.ForeignKey(blank=True, help_text='Related Practice Lab challenge progress', null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice.challengeprogress')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Quiz Attempt',
                'verbose_name_plural': 'Student Quiz Attempts',
                'db_table': 'student_quiz_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'chapter_quiz'], name='student_qui_student_37db5d_idx'), models.Index(fields=['student', '-created_at'], name='student_qui_student_67d2ee_idx'), models.Index(fields=['is_completed', 'is_passed'], name='student_qui_is_comp_21ac5b_idx')],
                'unique_together': {('student', 'chapter_quiz', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ChapterResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('title', models.CharField(help_text='Resource title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Resource description')),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document'), ('LINK', 'External Link'), ('VIDEO', 'Supplementary Video'), ('CODE', 'Code Examples'), ('WORKSHEET', 'Exercise Worksheet'), ('AUDIO', 'Audio File'), ('IMAGE', 'Image/Infographic')], help_text='Type of resource', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Uploaded file', null=True, upload_to='chapter_resources/')),
                ('external_url', models.URLField(blank=True, help_text='External URL')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of downloads')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently in resources tab')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.chapter')),
                ('created_by', models.ForeignKey(help_text='Teacher who created this resource', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter Resource',
                'verbose_name_plural': 'Chapter Resources',
                'db_table': 'chapter_resources',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['chapter', 'order'], name='chapter_res_chapter_d369b3_idx'), models.Index(fields=['resource_type'], name='chapter_res_resourc_5b3884_idx'), models.Index(fields=['is_featured'], name='chapter_res_is_feat_9ea358_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chapterquiz',
            index=models.Index(fields=['is_active'], name='chapter_qui_is_acti_b09fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterquiz',
            index=models.Index(fields=['created_by'], name='chapter_qui_created_69e5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterquiz',
            index=models.Index(fields=['practice_lesson'], name='chapter_qui_practic_b483f4_idx'),
        ),
    ]
