# Generated by Django 4.2.24 on 2025-09-14 16:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterResourceTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
            ],
            options={
                'verbose_name': 'Chapter Resource Tag',
                'verbose_name_plural': 'Chapter Resource Tags',
                'db_table': 'chapter_resource_tags',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('action', models.CharField(help_text='Action performed (enrolled, deactivated, reactivated, etc.)', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
            ],
            options={
                'verbose_name': 'Enrollment Log',
                'verbose_name_plural': 'Enrollment Logs',
                'db_table': 'enrollment_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], help_text='Type of payment method', max_length=20)),
                ('last_four', models.CharField(blank=True, help_text='Last 4 digits of card number', max_length=4)),
                ('card_brand', models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=20)),
                ('exp_month', models.PositiveIntegerField(blank=True, help_text='Card expiration month', null=True)),
                ('exp_year', models.PositiveIntegerField(blank=True, help_text='Card expiration year', null=True)),
                ('provider_id', models.CharField(help_text="Payment provider's ID for this method", max_length=255)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', help_text='Payment provider', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default payment method")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for this model')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('ordering', 'Ordering')], help_text='Type of question', max_length=20)),
                ('question_text', models.TextField(help_text='The question text')),
                ('image', models.URLField(blank=True, help_text='Optional image for the question')),
                ('audio', models.URLField(blank=True, help_text='Optional audio for the question')),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the quiz')),
                ('options', models.JSONField(default=list, help_text='Question options and correct answers (format varies by type)')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'db_table': 'quiz_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('share', 'Share')], help_text='Type of access', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the access', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier', max_length=50)),
            ],
            options={
                'verbose_name': 'Resource Access Log',
                'verbose_name_plural': 'Resource Access Logs',
                'db_table': 'resource_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('color', models.CharField(default='#007bff', help_text='Category color (hex code)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon class or name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the category is active')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'db_table': 'resource_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Tag color (hex code)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Tag description')),
            ],
            options={
                'verbose_name': 'Resource Tag',
                'verbose_name_plural': 'Resource Tags',
                'db_table': 'resource_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('action', models.CharField(help_text='Action performed (created, completed, failed, refunded, etc.)', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount related to this action (if applicable)', max_digits=10, null=True)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('provider_reference', models.CharField(blank=True, help_text='Payment provider reference for this action', max_length=255)),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'db_table': 'transaction_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for this model'),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Whether this comment/question has been resolved'),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.chaptercomment'),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of attempts for this chapter'),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='best_score',
            field=models.FloatField(blank=True, help_text='Best score achieved on this chapter (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='notes',
            field=models.TextField(blank=True, help_text="User's personal notes for this chapter"),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent on this chapter (minutes)'),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='allow_review',
            field=models.BooleanField(default=True, help_text='Whether students can review their answers'),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='When the quiz becomes available', null=True),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='When the quiz stops being available', null=True),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', help_text='Quiz difficulty level', max_length=10),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for this model'),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='randomize_questions',
            field=models.BooleanField(default=True, help_text='Whether to randomize question order'),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='show_correct_answers',
            field=models.BooleanField(default=True, help_text='Whether to show correct answers after completion'),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='access_level',
            field=models.CharField(choices=[('free', 'Free Access'), ('enrolled', 'Enrolled Students Only'), ('premium', 'Premium Students Only'), ('teacher', 'Teachers Only')], default='enrolled', help_text='Who can access this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='When the resource becomes available', null=True),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='When the resource stops being available', null=True),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='file_format',
            field=models.CharField(blank=True, help_text='File format/extension', max_length=20),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the resource is currently active'),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='is_downloadable',
            field=models.BooleanField(default=True, help_text='Whether the resource can be downloaded'),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for this model'),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of views'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='enrollment_source',
            field=models.CharField(default='direct', help_text='Source of enrollment (direct, promotion, gift, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this enrollment expires (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the enrollment is currently active'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='answers_data',
            field=models.JSONField(default=dict, help_text="Student's answers and question data"),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for this model'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the attempt was started'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='EUR', help_text='Transaction currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the transaction', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for this model'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment provider fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Payment intent ID from payment provider', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Reason for refund'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded (if any)', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When the refund was processed', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', help_text='Current transaction status', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='completion_date',
            field=models.DateTimeField(blank=True, help_text='When the course was completed (if completed)', null=True),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='current_chapter',
            field=models.ForeignKey(blank=True, help_text='Current chapter user is working on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='total_time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Total time spent in course (minutes)'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='chapterprogress',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether this item has been completed'),
        ),
        migrations.AlterField(
            model_name='chapterprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this item was completed', null=True),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum attempts allowed', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=80, help_text='Minimum score percentage to pass', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Total attempts by all users'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddIndex(
            model_name='chaptercomment',
            index=models.Index(fields=['parent_comment'], name='chapter_com_parent__879a09_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterprogress',
            index=models.Index(fields=['completed_at'], name='chapter_pro_complet_f30e88_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterquiz',
            index=models.Index(fields=['difficulty'], name='chapter_qui_difficu_6060de_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterquiz',
            index=models.Index(fields=['available_from', 'available_until'], name='chapter_qui_availab_8113b4_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterresource',
            index=models.Index(fields=['is_active'], name='chapter_res_is_acti_2fa2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterresource',
            index=models.Index(fields=['access_level'], name='chapter_res_access__ba5023_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterresource',
            index=models.Index(fields=['created_by'], name='chapter_res_created_2cc19a_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['is_active'], name='course_enro_is_acti_3aaf39_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['chapter_quiz', 'is_completed'], name='student_qui_chapter_5787eb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['paymentProvider'], name='transaction_payment_d6c5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'dateTime'], name='transaction_status_1d912a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='transaction_user_id_08c743_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['overallProgress'], name='user_course_overall_e8726d_idx'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='courses.transaction'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to='courses.course'),
        ),
        migrations.AddField(
            model_name='resourceaccesslog',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='courses.chapterresource'),
        ),
        migrations.AddField(
            model_name='resourceaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who accessed the resource (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.chapterquiz'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentlog',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='courses.courseenrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterresourcetag',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_tags', to='courses.chapterresource'),
        ),
        migrations.AddField(
            model_name='chapterresourcetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.resourcetag'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction'], name='transaction_transac_567f79_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['action'], name='transaction_action_6a790c_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['created_at'], name='transaction_created_644523_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecategory',
            index=models.Index(fields=['course', 'order'], name='resource_ca_course__6f89df_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecategory',
            index=models.Index(fields=['is_active'], name='resource_ca_is_acti_20f31d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcecategory',
            unique_together={('course', 'name')},
        ),
        migrations.AddIndex(
            model_name='resourceaccesslog',
            index=models.Index(fields=['resource', '-created_at'], name='resource_ac_resourc_a2aa80_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccesslog',
            index=models.Index(fields=['user', '-created_at'], name='resource_ac_user_id_07a5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccesslog',
            index=models.Index(fields=['access_type'], name='resource_ac_access__8a8336_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccesslog',
            index=models.Index(fields=['created_at'], name='resource_ac_created_793c42_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'order'], name='quiz_questi_quiz_id_76bc24_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['question_type'], name='quiz_questi_questio_4b375f_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['is_active'], name='quiz_questi_is_acti_260010_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user'], name='payment_met_user_id_6649e0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['type'], name='payment_met_type_e77616_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['is_default'], name='payment_met_is_defa_11be74_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['is_active'], name='payment_met_is_acti_395fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentlog',
            index=models.Index(fields=['enrollment'], name='enrollment__enrollm_19f261_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentlog',
            index=models.Index(fields=['action'], name='enrollment__action_1978bd_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentlog',
            index=models.Index(fields=['created_at'], name='enrollment__created_e8aaf9_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterresourcetag',
            index=models.Index(fields=['resource'], name='chapter_res_resourc_93c7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterresourcetag',
            index=models.Index(fields=['tag'], name='chapter_res_tag_id_e07f2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapterresourcetag',
            unique_together={('resource', 'tag')},
        ),
    ]
