# Generated by Django 4.2.24 on 2025-09-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_chapterresourcetag_enrollmentlog_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('video', 'Curso de Vídeo'), ('practice', 'Curso do Laboratório')], default='video', help_text='Type of course: video lessons or practice laboratory', max_length=20),
        ),
    ]
