# Generated by Django 4.2.24 on 2025-09-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='avg_listening_score',
            field=models.FloatField(default=0.0, help_text='Pontuação média nas práticas de listening'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='avg_speaking_score',
            field=models.FloatField(default=0.0, help_text='Pontuação média nas práticas de speaking'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='listening_practice_progress',
            field=models.JSONField(default=dict, help_text='Progresso nas práticas de listening específicas do curso'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='speaking_practice_progress',
            field=models.JSONField(default=dict, help_text='Progresso nas práticas de speaking específicas do curso'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='total_listening_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Total de sessões de listening completadas'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='total_speaking_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Total de sessões de speaking completadas'),
        ),
    ]
