# Generated by Django 4.2.24 on 2025-09-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_usercourseprogress_avg_listening_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
