# Generated by Django 4.2.24 on 2025-10-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_add_quiz_data_practice_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='template',
            field=models.CharField(choices=[('general', 'Inglês Geral'), ('oil-gas', 'Inglês para Petróleo & Gás'), ('banking', 'Inglês Bancário'), ('technology', 'Inglês para TI & Telecomunicações'), ('executive', 'Inglês Executivo'), ('ai-personal', 'Inglês com IA Personal Tutor'), ('business', 'Inglês para Negócios'), ('medical', 'Inglês Médico'), ('legal', 'Inglês Jurídico')], default='general', help_text='Course template type for styling and content focus', max_length=20),
        ),
    ]
