# Generated by Django 4.2.24 on 2026-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(help_text='Chapter content - sem limite para conteúdo rico'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(help_text='Chapter title', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Course description (sem limite para conteúdo rico)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='Curso sem título', help_text='Course title', max_length=500),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='sectionDescription',
            field=models.TextField(blank=True, help_text='Section description (sem limite para conteúdo rico)'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='sectionTitle',
            field=models.CharField(help_text='Section title', max_length=500),
        ),
    ]
