# Generated by Django 4.2.24 on 2026-01-27 21:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_increase_field_limits_hybrid_approach'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('quiz_score', models.FloatField(default=0.0, help_text='Average quiz score (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quiz_count', models.PositiveIntegerField(default=0, help_text='Total quizzes in course')),
                ('quiz_completed', models.PositiveIntegerField(default=0, help_text='Quizzes completed by student')),
                ('quiz_passed', models.PositiveIntegerField(default=0, help_text='Quizzes passed by student')),
                ('quiz_details', models.JSONField(default=list, help_text='Detailed scores per quiz')),
                ('practice_score', models.FloatField(default=0.0, help_text='Practice completion percentage (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('practice_count', models.PositiveIntegerField(default=0, help_text='Total practice exercises')),
                ('practice_completed', models.PositiveIntegerField(default=0, help_text='Practice exercises completed')),
                ('practice_details', models.JSONField(default=list, help_text='Detailed progress per chapter')),
                ('conversation_score', models.FloatField(default=0.0, help_text='Average Vapi conversation score (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conversation_sessions', models.PositiveIntegerField(default=0, help_text='Total conversation sessions')),
                ('conversation_minutes', models.PositiveIntegerField(default=0, help_text='Total conversation minutes')),
                ('conversation_details', models.JSONField(default=list, help_text='Detailed session scores')),
                ('has_conversation_requirement', models.BooleanField(default=False, help_text='Whether course requires conversation practice')),
                ('final_grade_percentage', models.FloatField(default=0.0, help_text='Calculated final grade (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_grade_letter', models.CharField(choices=[('A+', 'A+ (Exceptional)'), ('A', 'A (Excellent)'), ('A-', 'A- (Very Good)'), ('B+', 'B+ (Good)'), ('B', 'B (Above Average)'), ('B-', 'B- (Satisfactory)'), ('C+', 'C+ (Average)'), ('C', 'C (Adequate)'), ('C-', 'C- (Below Average)'), ('D+', 'D+ (Poor)'), ('D', 'D (Very Poor)'), ('F', 'F (Fail)')], default='F', max_length=2)),
                ('is_eligible_for_certificate', models.BooleanField(default=False, help_text='Whether all minimum requirements are met')),
                ('eligibility_details', models.JSONField(default=dict, help_text='Details of each requirement (met/not met)')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, help_text='Last grade calculation timestamp')),
                ('calculation_version', models.PositiveIntegerField(default=1, help_text='Version of calculation algorithm used')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Course Grade',
                'verbose_name_plural': 'Student Course Grades',
                'db_table': 'student_course_grades',
            },
        ),
        migrations.CreateModel(
            name='StudentBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('timestamp', models.PositiveIntegerField(blank=True, help_text='Video timestamp in seconds (if applicable)', null=True)),
                ('note', models.CharField(blank=True, help_text='Optional note about this bookmark', max_length=500)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='courses.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Bookmark',
                'verbose_name_plural': 'Student Bookmarks',
                'db_table': 'student_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('quiz_score', models.FloatField()),
                ('practice_score', models.FloatField()),
                ('conversation_score', models.FloatField()),
                ('final_grade_percentage', models.FloatField()),
                ('final_grade_letter', models.CharField(max_length=2)),
                ('is_eligible', models.BooleanField()),
                ('change_reason', models.CharField(choices=[('quiz_completed', 'Quiz Completed'), ('quiz_retake', 'Quiz Retake'), ('practice_completed', 'Practice Completed'), ('conversation_session', 'Conversation Session'), ('manual_adjustment', 'Manual Adjustment'), ('recalculation', 'Automatic Recalculation'), ('config_change', 'Grading Config Changed'), ('initial', 'Initial Calculation')], max_length=50)),
                ('change_details', models.JSONField(default=dict, help_text='Additional details about the change')),
                ('student_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='courses.studentcoursegrade')),
            ],
            options={
                'verbose_name': 'Grade History',
                'verbose_name_plural': 'Grade Histories',
                'db_table': 'grade_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseWishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Wishlist',
                'verbose_name_plural': 'Course Wishlists',
                'db_table': 'course_wishlist',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Review title', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Review content')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the reviewer completed the course')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of users who found this review helpful')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'db_table': 'course_reviews',
            },
        ),
        migrations.CreateModel(
            name='CourseGradingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('quiz_weight', models.PositiveIntegerField(default=50, help_text='Weight of quizzes in final grade (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('practice_weight', models.PositiveIntegerField(default=30, help_text='Weight of practice exercises in final grade (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conversation_weight', models.PositiveIntegerField(default=20, help_text='Weight of Vapi conversations in final grade (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_quiz_average', models.FloatField(default=70.0, help_text='Minimum quiz average required (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_practice_completion', models.FloatField(default=80.0, help_text='Minimum practice completion percentage (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_conversation_score', models.FloatField(default=60.0, help_text='Minimum Vapi conversation score (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_final_grade', models.FloatField(default=70.0, help_text='Minimum final grade for certificate (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('require_all_quizzes_passed', models.BooleanField(default=True, help_text='Require all quizzes to be individually passed')),
                ('allow_quiz_retakes', models.BooleanField(default=True, help_text='Allow students to retake quizzes to improve grade')),
                ('use_best_quiz_attempt', models.BooleanField(default=True, help_text='Use best attempt for each quiz (vs latest)')),
                ('require_conversation_if_available', models.BooleanField(default=True, help_text='Require conversation practice if course has it')),
                ('grade_a_min', models.FloatField(default=90.0, help_text='Minimum percentage for grade A', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_b_min', models.FloatField(default=80.0, help_text='Minimum percentage for grade B', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_c_min', models.FloatField(default=70.0, help_text='Minimum percentage for grade C', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_d_min', models.FloatField(default=60.0, help_text='Minimum percentage for grade D (below is F)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_config', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Grading Configuration',
                'verbose_name_plural': 'Course Grading Configurations',
                'db_table': 'course_grading_config',
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('certificate_number', models.CharField(help_text='Unique certificate identifier', max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='When the certificate was issued')),
                ('completion_percentage', models.FloatField(default=100.0, help_text='Course completion percentage at time of certificate')),
                ('final_grade', models.FloatField(blank=True, help_text='Final grade/score if applicable', null=True)),
                ('certificate_url', models.URLField(blank=True, help_text='URL to the certificate PDF')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Certificate',
                'verbose_name_plural': 'Course Certificates',
                'db_table': 'course_certificates',
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('content', models.TextField(help_text='Note content')),
                ('timestamp', models.PositiveIntegerField(blank=True, help_text='Video timestamp in seconds (if applicable)', null=True)),
                ('chapter', models.ForeignKey(blank=True, help_text='Optional: specific chapter this note relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='courses.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Note',
                'verbose_name_plural': 'Student Notes',
                'db_table': 'student_notes',
                'indexes': [models.Index(fields=['user', 'course'], name='student_not_user_id_c2ced7_idx'), models.Index(fields=['chapter'], name='student_not_chapter_ca209a_idx'), models.Index(fields=['-created_at'], name='student_not_created_fdadd3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studentcoursegrade',
            index=models.Index(fields=['user', '-final_grade_percentage'], name='student_cou_user_id_a85542_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcoursegrade',
            index=models.Index(fields=['course', '-final_grade_percentage'], name='student_cou_course__53d4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcoursegrade',
            index=models.Index(fields=['is_eligible_for_certificate'], name='student_cou_is_elig_8cd02d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcoursegrade',
            index=models.Index(fields=['final_grade_letter'], name='student_cou_final_g_f6266f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcoursegrade',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='studentbookmark',
            index=models.Index(fields=['user', '-created_at'], name='student_boo_user_id_1b1370_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbookmark',
            index=models.Index(fields=['chapter'], name='student_boo_chapter_14b340_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbookmark',
            unique_together={('user', 'chapter', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['student_grade', '-created_at'], name='grade_histo_student_7acac0_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['change_reason'], name='grade_histo_change__179fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='coursewishlist',
            index=models.Index(fields=['user', '-added_at'], name='course_wish_user_id_0ebfa5_idx'),
        ),
        migrations.AddIndex(
            model_name='coursewishlist',
            index=models.Index(fields=['course'], name='course_wish_course__11379a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursewishlist',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', '-created_at'], name='course_revi_course__16a41f_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['user'], name='course_revi_user_id_78bf03_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['rating'], name='course_revi_rating_0836d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='coursecertificate',
            index=models.Index(fields=['user'], name='course_cert_user_id_2082f6_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecertificate',
            index=models.Index(fields=['course'], name='course_cert_course__2a600e_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecertificate',
            index=models.Index(fields=['certificate_number'], name='course_cert_certifi_ec15ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecertificate',
            unique_together={('user', 'course')},
        ),
    ]
