# Generated by Django 4.2.24 on 2026-01-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_grading_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecertificate',
            name='final_grade_letter',
            field=models.CharField(blank=True, help_text='Final grade letter (A+, A, B+, etc.)', max_length=2),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Code for certificate verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursecertificate',
            name='final_grade',
            field=models.FloatField(blank=True, help_text='Final grade percentage (0-100)', null=True),
        ),
    ]
