# Generated by Django 4.2.24 on 2026-01-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_certificate_grade_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegradingconfig',
            name='auto_adjust_weights',
            field=models.BooleanField(default=True, help_text="Automatically redistribute weights when components don't exist"),
        ),
        migrations.AddField(
            model_name='coursegradingconfig',
            name='conversation_enabled',
            field=models.BooleanField(default=True, help_text='Enable conversation practice for grading'),
        ),
        migrations.AddField(
            model_name='coursegradingconfig',
            name='practice_enabled',
            field=models.BooleanField(default=True, help_text='Enable practice exercises for grading'),
        ),
        migrations.AddField(
            model_name='coursegradingconfig',
            name='quiz_enabled',
            field=models.BooleanField(default=True, help_text='Enable quiz component for grading'),
        ),
        migrations.AddField(
            model_name='studentcoursegrade',
            name='weight_info',
            field=models.JSONField(default=dict, help_text='Information about weight adjustments applied'),
        ),
    ]
