# Generated by Django 4.2.24 on 2026-01-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_add_grading_config_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursegrade',
            name='final_grade_letter',
            field=models.CharField(choices=[('A+', 'A+ (Exceptional)'), ('A', 'A (Excellent)'), ('A-', 'A- (Very Good)'), ('B+', 'B+ (Good)'), ('B', 'B (Above Average)'), ('B-', 'B- (Satisfactory)'), ('C+', 'C+ (Average)'), ('C', 'C (Adequate)'), ('C-', 'C- (Below Average)'), ('D+', 'D+ (Poor)'), ('D', 'D (Very Poor)'), ('F', 'F (Fail)'), ('N/A', 'N/A (Not Available)')], default='F', max_length=3),
        ),
    ]
