# Generated by Django 4.2.24 on 2026-01-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_fix_grade_letter_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradehistory',
            name='final_grade_letter',
            field=models.CharField(max_length=3),
        ),
    ]
