# Generated by Django 4.2.24 on 2026-01-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_fix_grade_history_letter_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='practice_course',
            field=models.ForeignKey(blank=True, help_text='Associated Practice Lab course (only for video courses)', limit_choices_to={'course_type': 'practice'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_courses', to='courses.course'),
        ),
    ]
