# Generated by Django 4.2.24 on 2026-02-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_add_practice_course_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='practice_course',
        ),
        migrations.AddField(
            model_name='course',
            name='access_level',
            field=models.CharField(choices=[('free', 'Gratuito - Disponível para todos'), ('premium', 'Premium - Requer plano Premium ou superior'), ('premium_plus', 'Premium Plus - Exclusivo para Premium Plus')], default='free', help_text='Minimum subscription plan required to access this course', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this course is featured/highlighted on the platform'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['access_level'], name='courses_access__5f5076_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured'], name='courses_is_feat_29280c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'access_level'], name='course_status_access_idx'),
        ),
    ]
