# Generated by Django 4.2.24 on 2025-09-12 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('FREE', 'Gratuito'), ('PREMIUM', 'Premium'), ('PREMIUM_PLUS', 'Premium Plus')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Preço mensal em Kuanzas (AOA)', max_digits=10)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço anual em Kuanzas (AOA) - com desconto', max_digits=10, null=True)),
                ('daily_lessons_limit', models.IntegerField(blank=True, help_text='Limite diário de lições (null = ilimitado)', null=True)),
                ('daily_speaking_minutes', models.IntegerField(blank=True, help_text='Minutos diários de Speaking Practice (null = ilimitado)', null=True)),
                ('daily_listening_minutes', models.IntegerField(blank=True, help_text='Minutos diários de Listening Practice (null = ilimitado)', null=True)),
                ('hearts_limit', models.IntegerField(default=5, help_text='Número máximo de vidas (0 = ilimitado)')),
                ('hearts_recharge_hours', models.IntegerField(default=4, help_text='Horas para recarregar 1 vida (0 = sem recarga)')),
                ('offline_downloads', models.BooleanField(default=False)),
                ('certificates', models.BooleanField(default=False)),
                ('ai_tutor', models.BooleanField(default=False)),
                ('native_teacher_sessions', models.IntegerField(default=0, help_text='Sessões mensais com professores nativos')),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('streak_freeze', models.IntegerField(default=0, help_text='Freezes de streak por semana')),
                ('multiple_devices', models.IntegerField(default=1, help_text='Número de dispositivos simultâneos permitidos')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('CANCELED', 'Cancelada'), ('EXPIRED', 'Expirada'), ('PENDING', 'Pendente'), ('TRIAL', 'Período de Teste')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('daily_lessons_used', models.IntegerField(default=0)),
                ('daily_speaking_minutes_used', models.IntegerField(default=0)),
                ('daily_listening_minutes_used', models.IntegerField(default=0)),
                ('current_hearts', models.IntegerField(default=5)),
                ('last_heart_recharge', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Criada'), ('UPGRADED', 'Upgrade'), ('DOWNGRADED', 'Downgrade'), ('RENEWED', 'Renovada'), ('CANCELED', 'Cancelada'), ('EXPIRED', 'Expirada'), ('TRIAL_STARTED', 'Trial Iniciado'), ('TRIAL_ENDED', 'Trial Finalizado'), ('PAYMENT_SUCCESS', 'Pagamento Realizado'), ('PAYMENT_FAILED', 'Falha no Pagamento')], max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Valor pago em Kuanzas (AOA)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.subscriptionplan')),
                ('previous_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.subscriptionplan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.usersubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentual'), ('FIXED_AMOUNT', 'Valor Fixo'), ('FREE_TRIAL', 'Trial Gratuito')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Valor do desconto (% ou AOA)', max_digits=10)),
                ('max_uses', models.IntegerField(default=1)),
                ('current_uses', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('first_time_users_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, help_text='Planos elegíveis (vazio = todos)', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_applied', models.DecimalField(decimal_places=2, help_text='Desconto aplicado em AOA', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscriptions.promotionalcode')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='subscriptions.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('promo_code', 'user')},
            },
        ),
    ]
