# Generated by Django 4.2.24 on 2025-09-18 18:28

import apps.subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='last_reset_date',
            field=models.DateField(default=apps.subscriptions.models.get_current_date),
        ),
    ]
