# Generated by Django 4.2.24 on 2025-10-20 07:26

from django.db import migrations
from decimal import Decimal


def create_default_plans(apps, schema_editor):
    """Cria os planos de assinatura padrão."""
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    
    # Plano Gratuito
    SubscriptionPlan.objects.get_or_create(
        plan_type='FREE',
        defaults={
            'name': 'Plano Gratuito',
            'description': 'Acesso básico gratuito à plataforma Tuwi',
            'monthly_price': Decimal('0.00'),
            'yearly_price': Decimal('0.00'),
            'daily_lessons_limit': 3,
            'daily_speaking_minutes': 10,
            'daily_listening_minutes': 15,
            'hearts_limit': 5,
            'hearts_recharge_hours': 4,
            'offline_downloads': False,
            'certificates': False,
            'ai_tutor': False,
            'native_teacher_sessions': 0,
            'advanced_analytics': False,
            'priority_support': False,
            'streak_freeze': 0,
            'multiple_devices': 1,
            'is_active': True,
            'sort_order': 1
        }
    )
    
    # Plano Premium
    SubscriptionPlan.objects.get_or_create(
        plan_type='PREMIUM',
        defaults={
            'name': 'Tuwi Premium',
            'description': 'Acesso completo com recursos avançados',
            'monthly_price': Decimal('2500.00'),  # 2500 AOA
            'yearly_price': Decimal('25000.00'),  # 25000 AOA (desconto de ~16%)
            'daily_lessons_limit': 0,  # Ilimitado
            'daily_speaking_minutes': 0,  # Ilimitado
            'daily_listening_minutes': 0,  # Ilimitado
            'hearts_limit': 0,  # Ilimitado
            'hearts_recharge_hours': 0,
            'offline_downloads': True,
            'certificates': True,
            'ai_tutor': True,
            'native_teacher_sessions': 5,
            'advanced_analytics': True,
            'priority_support': True,
            'streak_freeze': 3,
            'multiple_devices': 3,
            'is_active': True,
            'sort_order': 2
        }
    )
    
    # Plano Premium Plus
    SubscriptionPlan.objects.get_or_create(
        plan_type='PREMIUM_PLUS',
        defaults={
            'name': 'Tuwi Premium Plus',
            'description': 'Experiência premium completa com tutor nativo',
            'monthly_price': Decimal('4000.00'),  # 4000 AOA
            'yearly_price': Decimal('40000.00'),  # 40000 AOA (desconto de ~16%)
            'daily_lessons_limit': 0,  # Ilimitado
            'daily_speaking_minutes': 0,  # Ilimitado
            'daily_listening_minutes': 0,  # Ilimitado
            'hearts_limit': 0,  # Ilimitado
            'hearts_recharge_hours': 0,
            'offline_downloads': True,
            'certificates': True,
            'ai_tutor': True,
            'native_teacher_sessions': 0,  # Ilimitado
            'advanced_analytics': True,
            'priority_support': True,
            'streak_freeze': 0,  # Ilimitado
            'multiple_devices': 0,  # Ilimitado
            'is_active': True,
            'sort_order': 3
        }
    )


def reverse_default_plans(apps, schema_editor):
    """Remove os planos padrão."""
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(
        plan_type__in=['FREE', 'PREMIUM', 'PREMIUM_PLUS']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_usersubscription_last_reset_date'),
    ]
    
    # Run this migration operation after all models are ready
    run_before = []

    operations = [
        migrations.RunPython(create_default_plans, reverse_default_plans),
    ]
