# Generated by Django 4.2.24 on 2025-10-20 22:50

from django.db import migrations
from decimal import Decimal


def ensure_default_plans(apps, schema_editor):
    """Ensure subscription plans exist, creating them if they don't."""
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    
    # Plans configuration
    plans_config = [
        {
            'plan_type': 'FREE',
            'name': 'Plano Gratuito',
            'description': 'Acesso básico gratuito à plataforma Tuwi',
            'monthly_price': Decimal('0.00'),
            'yearly_price': Decimal('0.00'),
            'daily_lessons_limit': 3,
            'daily_speaking_minutes': 10,
            'daily_listening_minutes': 15,
            'hearts_limit': 5,
            'hearts_recharge_hours': 4,
            'offline_downloads': False,
            'certificates': False,
            'ai_tutor': False,
            'native_teacher_sessions': 0,
            'advanced_analytics': False,
            'priority_support': False,
            'streak_freeze': 0,
            'multiple_devices': 1,
            'is_active': True,
            'sort_order': 1
        },
        {
            'plan_type': 'PREMIUM',
            'name': 'Tuwi Premium',
            'description': 'Acesso completo com recursos avançados',
            'monthly_price': Decimal('2500.00'),
            'yearly_price': Decimal('25000.00'),
            'daily_lessons_limit': 0,  # Unlimited
            'daily_speaking_minutes': 0,  # Unlimited
            'daily_listening_minutes': 0,  # Unlimited
            'hearts_limit': 0,  # Unlimited
            'hearts_recharge_hours': 0,
            'offline_downloads': True,
            'certificates': True,
            'ai_tutor': True,
            'native_teacher_sessions': 5,
            'advanced_analytics': True,
            'priority_support': True,
            'streak_freeze': 3,
            'multiple_devices': 3,
            'is_active': True,
            'sort_order': 2
        },
        {
            'plan_type': 'PREMIUM_PLUS',
            'name': 'Tuwi Premium Plus',
            'description': 'Experiência premium completa com tutor nativo',
            'monthly_price': Decimal('4000.00'),
            'yearly_price': Decimal('40000.00'),
            'daily_lessons_limit': 0,  # Unlimited
            'daily_speaking_minutes': 0,  # Unlimited
            'daily_listening_minutes': 0,  # Unlimited
            'hearts_limit': 0,  # Unlimited
            'hearts_recharge_hours': 0,
            'offline_downloads': True,
            'certificates': True,
            'ai_tutor': True,
            'native_teacher_sessions': 0,  # Unlimited
            'advanced_analytics': True,
            'priority_support': True,
            'streak_freeze': 0,  # Unlimited
            'multiple_devices': 0,  # Unlimited
            'is_active': True,
            'sort_order': 3
        }
    ]
    
    # Create plans that don't exist
    for plan_config in plans_config:
        plan, created = SubscriptionPlan.objects.get_or_create(
            plan_type=plan_config['plan_type'],
            defaults=plan_config
        )
        if created:
            print(f"Created subscription plan: {plan.name}")
        else:
            print(f"Subscription plan already exists: {plan.name}")


def reverse_ensure_plans(apps, schema_editor):
    """Remove the plans - only used if migration is reversed."""
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(
        plan_type__in=['FREE', 'PREMIUM', 'PREMIUM_PLUS']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_default_subscription_plans'),
    ]

    operations = [
        migrations.RunPython(ensure_default_plans, reverse_ensure_plans),
    ]