# Generated by Django 4.2.24 on 2026-02-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_set_ai_analyses_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='Dias de trial após cadastro (0 = sem trial)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_speaking_minutes',
            field=models.IntegerField(default=0, help_text='Minutos diários de speaking durante o trial'),
        ),
    ]
