# Generated by Django 5.2.5 on 2025-08-19 06:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('seasonal', 'Seasonal Campaign'), ('new_user', 'New User Campaign'), ('retention', 'User Retention'), ('product_launch', 'Product Launch'), ('referral', 'Referral Program'), ('loyalty', 'Loyalty Program'), ('flash_sale', 'Flash Sale'), ('general', 'General Promotion')], default='general', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_audience', models.JSONField(default=dict, help_text='Target audience criteria (user roles, locations, etc.)')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of users who can participate', null=True)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget allocated for this campaign', max_digits=10, null=True)),
                ('current_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current amount spent on this campaign', max_digits=10)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_conversions', models.PositiveIntegerField(default=0)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaigns/banners/')),
                ('banner_text', models.CharField(blank=True, max_length=500)),
                ('call_to_action', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='promotions__status_c8d952_idx'), models.Index(fields=['campaign_type'], name='promotions__campaig_9a130a_idx'), models.Index(fields=['start_date', 'end_date'], name='promotions__start_d_22f35f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Promotion code users can enter', max_length=50, unique=True)),
                ('description', models.TextField()),
                ('promotion_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed_amount', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping'), ('buy_x_get_y', 'Buy X Get Y'), ('first_booking', 'First Booking Discount'), ('loyalty_points', 'Loyalty Points Multiplier'), ('referral_bonus', 'Referral Bonus')], max_length=20)),
                ('applies_to', models.CharField(choices=[('all', 'All Services'), ('category', 'Service Category'), ('service', 'Specific Service'), ('braider', 'Specific Braider'), ('order_total', 'Order Total')], default='all', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage discounts', max_digits=10, null=True)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount to qualify', max_digits=10, null=True)),
                ('maximum_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order amount to qualify', max_digits=10, null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='Maximum uses per user', null=True)),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum total uses across all users', null=True)),
                ('current_usage_count', models.PositiveIntegerField(default=0)),
                ('target_services', models.JSONField(blank=True, default=list, help_text='List of service IDs this promotion applies to')),
                ('target_categories', models.JSONField(blank=True, default=list, help_text='List of service categories this promotion applies to')),
                ('target_braiders', models.JSONField(blank=True, default=list, help_text='List of braider IDs this promotion applies to')),
                ('buy_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity to buy for Buy X Get Y promotions', null=True)),
                ('get_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity to get free for Buy X Get Y promotions', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_stackable', models.BooleanField(default=False, help_text='Can be combined with other promotions')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='promotions.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_coupons', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_codes', to='promotions.promotion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_usages', to='bookings.booking')),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='promotions.couponcode')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_conversions', models.PositiveIntegerField(default=0)),
                ('total_discount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='promotions.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['campaign', 'is_active'], name='promotions__campaig_57121c_idx'), models.Index(fields=['user', 'is_active'], name='promotions__user_id_26f0b2_idx')],
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code'], name='promotions__code_e9f529_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['promotion_type'], name='promotions__promoti_f59ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active'], name='promotions__is_acti_fc6f30_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['campaign', 'is_active'], name='promotions__campaig_1dcebf_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['code'], name='promotions__code_c95e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['promotion', 'is_used'], name='promotions__promoti_039ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['assigned_to'], name='promotions__assigne_092184_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['expires_at'], name='promotions__expires_552176_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['promotion', 'user'], name='promotions__promoti_ac6da2_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['user', '-created_at'], name='promotions__user_id_0285b3_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['booking'], name='promotions__booking_77e410_idx'),
        ),
    ]
