# Generated by Django 4.2.24 on 2025-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicechallenge',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select - Multiple Choice'), ('ASSIST', 'Assist - Translation/Help'), ('FILL_BLANK', 'Fill in the Blank'), ('TRANSLATION', 'Translation'), ('LISTENING', 'Listening Comprehension'), ('SPEAKING', 'Speaking/Pronunciation'), ('MATCH_PAIRS', 'Match Pairs'), ('SENTENCE_ORDER', 'Sentence Order')], help_text='Type of challenge exercise', max_length=20),
        ),
    ]
