# Generated by Django 4.2.24 on 2025-09-10 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0003_competition_userstreak_userleague_leaguepromotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or unicode icon', max_length=10)),
                ('category', models.CharField(choices=[('learning', 'Learning'), ('streak', 'Streak'), ('social', 'Social'), ('milestone', 'Milestone'), ('special', 'Special')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('points', models.PositiveIntegerField(help_text='Points awarded when unlocked')),
                ('requirement_type', models.CharField(help_text='Type of requirement: lessons_completed, streak_days, points_earned, etc.', max_length=50)),
                ('requirement_target', models.PositiveIntegerField(help_text="Target value to achieve (e.g., 50 for '50 lessons completed')")),
                ('requirement_unit', models.CharField(default='items', help_text='Unit for progress display (lessons, days, points, etc.)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False, help_text='Hidden achievements not shown until unlocked')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'category', 'rarity'],
            },
        ),
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='CSS icon class', max_length=50)),
                ('color', models.CharField(help_text='CSS color class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Achievement Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('current_progress', models.PositiveIntegerField(default=0, help_text='Current progress towards the achievement')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='practice.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at', '-created_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='AchievementNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_celebrated', models.BooleanField(default=False, help_text='Whether the achievement popup was shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='practice.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
