# Generated by Django 4.2.24 on 2025-09-11 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_chapter_practice_lesson_chapter_quiz_enabled_and_more'),
        ('practice', '0004_achievement_achievementcategory_userachievement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('PRONUNCIATION', 'Pronunciation Practice'), ('CONVERSATION', 'AI Conversation'), ('READING_ALOUD', 'Reading Aloud'), ('ROLE_PLAY', 'Role Playing'), ('STORY_TELLING', 'Story Telling'), ('VOCABULARY_PRACTICE', 'Vocabulary Practice')], max_length=20)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=15)),
                ('target_text', models.TextField(help_text='Texto alvo para leitura/repetição')),
                ('conversation_prompt', models.TextField(blank=True, help_text='Prompt inicial para conversação')),
                ('vocabulary_words', models.JSONField(default=list, help_text='Lista de palavras-chave para praticar')),
                ('pronunciation_weight', models.FloatField(default=0.4, help_text='Peso da pronúncia na nota (0-1)')),
                ('fluency_weight', models.FloatField(default=0.3, help_text='Peso da fluência na nota (0-1)')),
                ('accuracy_weight', models.FloatField(default=0.3, help_text='Peso da precisão na nota (0-1)')),
                ('points_reward', models.IntegerField(default=25)),
                ('hearts_cost', models.IntegerField(default=1)),
                ('minimum_score', models.FloatField(default=70.0, help_text='Pontuação mínima para passar (%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_exercises', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_speaking_exercises', to=settings.AUTH_USER_MODEL)),
                ('practice_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_exercises', to='practice.practicelesson')),
            ],
            options={
                'ordering': ['difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('turns_count', models.IntegerField(default=0, help_text='Número de falas do usuário')),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('pronunciation_score', models.FloatField(blank=True, null=True)),
                ('fluency_score', models.FloatField(blank=True, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('hearts_used', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('ai_feedback', models.TextField(blank=True)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='practice.speakingexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='practicechallenge',
            name='conversation_context',
            field=models.JSONField(default=dict, help_text='Contexto e cenário para conversação'),
        ),
        migrations.AddField(
            model_name='practicechallenge',
            name='minimum_speaking_score',
            field=models.FloatField(default=70.0, help_text='Pontuação mínima para passar no speaking'),
        ),
        migrations.AddField(
            model_name='practicechallenge',
            name='target_pronunciation',
            field=models.TextField(blank=True, help_text='Texto alvo para exercícios de pronúncia'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='average_fluency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='average_pronunciation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_speaking_session',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='speaking_streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_speaking_minutes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_speaking_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='practicechallenge',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select - Multiple Choice'), ('ASSIST', 'Assist - Translation/Help'), ('FILL_BLANK', 'Fill in the Blank'), ('TRANSLATION', 'Translation'), ('LISTENING', 'Listening Comprehension'), ('SPEAKING', 'Speaking/Pronunciation'), ('MATCH_PAIRS', 'Match Pairs'), ('SENTENCE_ORDER', 'Sentence Order'), ('PRONUNCIATION', 'Pronunciation Practice'), ('CONVERSATION', 'AI Conversation'), ('READING_ALOUD', 'Reading Aloud'), ('VOCABULARY_SPEAKING', 'Vocabulary Speaking')], help_text='Type of challenge exercise', max_length=20),
        ),
        migrations.CreateModel(
            name='SpeakingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_hours_practiced', models.FloatField(default=0.0)),
                ('total_words_spoken', models.IntegerField(default=0)),
                ('average_pronunciation', models.FloatField(default=0.0)),
                ('average_fluency', models.FloatField(default=0.0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('overall_average', models.FloatField(default=0.0)),
                ('beginner_sessions', models.IntegerField(default=0)),
                ('intermediate_sessions', models.IntegerField(default=0)),
                ('advanced_sessions', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('weak_phonemes', models.JSONField(default=list)),
                ('strong_areas', models.JSONField(default=list)),
                ('practice_recommendations', models.JSONField(default=list)),
                ('last_session_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='practicechallenge',
            name='speaking_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_challenges', to='practice.speakingexercise'),
        ),
        migrations.CreateModel(
            name='SpeakingTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.IntegerField()),
                ('turn_type', models.CharField(choices=[('USER_SPEECH', 'User Speech'), ('AI_RESPONSE', 'AI Response'), ('SYSTEM_PROMPT', 'System Prompt')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audio_url', models.URLField(blank=True, help_text='URL do arquivo de áudio gravado')),
                ('transcribed_text', models.TextField(blank=True, help_text='Texto transcrito da fala')),
                ('target_text', models.TextField(blank=True, help_text='Texto alvo para comparação')),
                ('ai_response_text', models.TextField(blank=True, help_text='Resposta da IA')),
                ('pronunciation_score', models.FloatField(blank=True, null=True)),
                ('fluency_score', models.FloatField(blank=True, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('words_analysis', models.JSONField(default=dict, help_text='Análise palavra por palavra')),
                ('pronunciation_errors', models.JSONField(default=list)),
                ('grammar_errors', models.JSONField(default=list)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='practice.speakingsession')),
            ],
            options={
                'ordering': ['turn_number'],
                'unique_together': {('session', 'turn_number')},
            },
        ),
    ]
