# Generated by Django 4.2.24 on 2025-09-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_usercourseprogress_avg_listening_score_and_more'),
        ('practice', '0006_listeningexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningexercise',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Indica se o exercício foi gerado automaticamente baseado no conteúdo do curso'),
        ),
        migrations.AddField(
            model_name='listeningexercise',
            name='is_course_specific',
            field=models.BooleanField(default=False, help_text='Indica se o exercício é específico para um curso ou genérico'),
        ),
        migrations.AddField(
            model_name='listeningexercise',
            name='lesson_context',
            field=models.CharField(blank=True, help_text="Contexto da lição específica (ex: 'Business Meetings', 'Family Vocabulary')", max_length=200),
        ),
        migrations.AddField(
            model_name='speakingexercise',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Indica se o exercício foi gerado automaticamente baseado no conteúdo do curso'),
        ),
        migrations.AddField(
            model_name='speakingexercise',
            name='is_course_specific',
            field=models.BooleanField(default=False, help_text='Indica se o exercício é específico para um curso ou genérico'),
        ),
        migrations.AddField(
            model_name='speakingexercise',
            name='lesson_context',
            field=models.CharField(blank=True, help_text="Contexto da lição específica (ex: 'Business Meetings', 'Family Vocabulary')", max_length=200),
        ),
        migrations.AlterField(
            model_name='listeningexercise',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Curso específico para exercício contextualizado (opcional para exercícios genéricos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_exercises', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='practicechallenge',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select - Multiple Choice'), ('ASSIST', 'Assist - Translation/Help'), ('FILL_BLANK', 'Fill in the Blank'), ('TRANSLATION', 'Translation'), ('LISTENING', 'Listening Comprehension'), ('SPEAKING', 'Speaking/Pronunciation'), ('MATCH_PAIRS', 'Match Pairs'), ('SENTENCE_ORDER', 'Sentence Order'), ('TRUE_FALSE', 'True/False Questions'), ('PRONUNCIATION', 'Pronunciation Practice'), ('CONVERSATION', 'AI Conversation'), ('READING_ALOUD', 'Reading Aloud'), ('VOCABULARY_SPEAKING', 'Vocabulary Speaking'), ('AUDIO_COMPREHENSION', 'Audio Comprehension'), ('DICTATION', 'Dictation Practice'), ('CONVERSATION_LISTENING', 'Conversation Listening'), ('ACCENT_RECOGNITION', 'Accent Recognition'), ('SPEED_LISTENING', 'Speed Listening')], help_text='Type of challenge exercise', max_length=25),
        ),
        migrations.AlterField(
            model_name='speakingexercise',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Curso específico para exercício contextualizado (opcional para exercícios genéricos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_exercises', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='listeningexercise',
            index=models.Index(fields=['course', 'is_course_specific'], name='practice_li_course__c2e06e_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningexercise',
            index=models.Index(fields=['is_course_specific', 'exercise_type'], name='practice_li_is_cour_ba4578_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingexercise',
            index=models.Index(fields=['course', 'is_course_specific'], name='practice_sp_course__ab9ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingexercise',
            index=models.Index(fields=['is_course_specific', 'exercise_type'], name='practice_sp_is_cour_3aa78a_idx'),
        ),
    ]
