# Generated by Django 4.2.24 on 2025-11-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_listeningexercise_auto_generated_and_more'),
    ]

    operations = [
        # Remove foreign key references first
        migrations.RemoveField(
            model_name='practicechallenge',
            name='speaking_exercise',
        ),
        migrations.RemoveField(
            model_name='practicechallenge',
            name='listening_exercise',
        ),
        
        # Remove speaking-related fields from PracticeChallenge
        migrations.RemoveField(
            model_name='practicechallenge',
            name='conversation_context',
        ),
        migrations.RemoveField(
            model_name='practicechallenge',
            name='minimum_speaking_score',
        ),
        migrations.RemoveField(
            model_name='practicechallenge',
            name='target_pronunciation',
        ),
        
        # Remove listening-related fields from PracticeChallenge
        migrations.RemoveField(
            model_name='practicechallenge',
            name='audio_content_url',
        ),
        migrations.RemoveField(
            model_name='practicechallenge',
            name='audio_transcript',
        ),
        migrations.RemoveField(
            model_name='practicechallenge',
            name='listening_questions',
        ),
        migrations.RemoveField(
            model_name='practicechallenge',
            name='minimum_listening_score',
        ),
        
        # Remove speaking-related fields from UserProgress
        migrations.RemoveField(
            model_name='userprogress',
            name='average_fluency_score',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='average_pronunciation_score',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_speaking_session',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='speaking_streak_days',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='total_speaking_minutes',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='total_speaking_sessions',
        ),
        
        # Remove listening-related fields from UserProgress (but keep some as they're now Vapi fields)
        migrations.RemoveField(
            model_name='userprogress',
            name='average_dictation_score',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_listening_session',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='listening_streak_days',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='total_listening_minutes',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='total_listening_sessions',
        ),
        
        # Rename average_comprehension_score to average_conversation_score for Vapi
        migrations.RenameField(
            model_name='userprogress',
            old_name='average_comprehension_score',
            new_name='average_conversation_score',
        ),
        
        # Add Vapi conversation fields to UserProgress
        migrations.AddField(
            model_name='userprogress',
            name='total_conversation_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_conversation_minutes',
            field=models.FloatField(default=0.0),
        ),
        
        # Delete the speaking and listening models (delete child models first)
        migrations.DeleteModel(name='SpeakingTurn'),
        migrations.DeleteModel(name='SpeakingSession'),
        migrations.DeleteModel(name='SpeakingProgress'),
        migrations.DeleteModel(name='SpeakingExercise'),
        
        migrations.DeleteModel(name='ListeningAttempt'),
        migrations.DeleteModel(name='ListeningSession'),
        migrations.DeleteModel(name='ListeningProgress'),
        migrations.DeleteModel(name='AudioSegment'),
        migrations.DeleteModel(name='ListeningExercise'),
        
        # Update PracticeChallenge type choices to remove obsolete speaking/listening types
        migrations.AlterField(
            model_name='practicechallenge',
            name='type',
            field=models.CharField(
                choices=[
                    ('SELECT', 'Select - Multiple Choice'),
                    ('ASSIST', 'Assist - Translation/Help'),
                    ('FILL_BLANK', 'Fill in the Blank'),
                    ('TRANSLATION', 'Translation'),
                    ('MATCH_PAIRS', 'Match Pairs'),
                    ('SENTENCE_ORDER', 'Sentence Order'),
                    ('VAPI_CONVERSATION', 'Vapi AI Conversation'),  # New Vapi type
                ],
                help_text='Type of challenge exercise',
                max_length=25
            ),
        ),
    ]
