# Generated by Django 4.2.24 on 2025-11-25 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0008_remove_speaking_listening_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicechallenge',
            name='conversation_context',
            field=models.JSONField(default=dict, help_text='Contexto e cenário para conversação com Vapi AI'),
        ),
        migrations.AddField(
            model_name='practicechallenge',
            name='minimum_conversation_score',
            field=models.FloatField(default=70.0, help_text='Pontuação mínima para passar na conversação'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='conversation_streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_conversation_session',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicechallenge',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select - Multiple Choice'), ('ASSIST', 'Assist - Translation/Help'), ('FILL_BLANK', 'Fill in the Blank'), ('TRANSLATION', 'Translation'), ('MATCH_PAIRS', 'Match Pairs'), ('SENTENCE_ORDER', 'Sentence Order'), ('TRUE_FALSE', 'True/False Questions'), ('VAPI_CONVERSATION', 'AI Conversation Practice')], help_text='Type of challenge exercise', max_length=25),
        ),
        migrations.CreateModel(
            name='VapiSession',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('level', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=50)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('fluency_score', models.PositiveIntegerField(default=0)),
                ('pronunciation_score', models.PositiveIntegerField(default=0)),
                ('grammar_score', models.PositiveIntegerField(default=0)),
                ('vocabulary_score', models.PositiveIntegerField(default=0)),
                ('overall_score', models.PositiveIntegerField(default=0)),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('words_per_minute', models.PositiveIntegerField(default=0)),
                ('corrections_count', models.PositiveIntegerField(default=0)),
                ('improvement_from_last', models.FloatField(default=0, help_text='Score improvement from last session')),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('full_session_data', models.JSONField(default=dict, help_text='Complete session data including corrections, phrases, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vapi_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='practice_va_user_id_2fb555_idx'), models.Index(fields=['user', 'level', '-date'], name='practice_va_user_id_d36810_idx'), models.Index(fields=['date'], name='practice_va_date_94d911_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyProgressSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('total_practice_minutes', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('total_corrections', models.PositiveIntegerField(default=0)),
                ('score_improvement', models.FloatField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('new_level_reached', models.BooleanField(default=False)),
                ('personal_best', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='practice_da_user_id_8e37b4_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
