# Generated by Django 4.2.24 on 2026-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_create_vapi_progress_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeoption',
            name='text',
            field=models.CharField(help_text='Option text/answer', max_length=300),
        ),
        migrations.AlterField(
            model_name='practicelesson',
            name='title',
            field=models.CharField(help_text='Lesson title', max_length=500),
        ),
        migrations.AlterField(
            model_name='practiceunit',
            name='description',
            field=models.TextField(help_text='Unit description - sem limite para conteúdo rico'),
        ),
        migrations.AlterField(
            model_name='practiceunit',
            name='title',
            field=models.CharField(help_text='Unit title', max_length=500),
        ),
    ]
