# Generated by Django 4.2.24 on 2026-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_increase_field_limits_hybrid_approach'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicechallenge',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after the challenge is answered', null=True),
        ),
        migrations.AddField(
            model_name='practicechallenge',
            name='hint',
            field=models.TextField(blank=True, help_text='Optional hint to help the student (shown on request)', null=True),
        ),
    ]
