# Generated by Django 4.2.24 on 2026-02-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_add_hint_explanation_to_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicechallenge',
            name='instruction',
            field=models.TextField(blank=True, help_text="General instruction for the exercise (e.g., 'Complete using I/You/am/are')", null=True),
        ),
    ]
