# Generated by Django 4.2.24 on 2026-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_add_instruction_to_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicechallenge',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select - Multiple Choice'), ('ASSIST', 'Assist - Translation/Help'), ('FILL_BLANK', 'Fill in the Blank'), ('TRANSLATION', 'Translation'), ('MATCH_PAIRS', 'Match Pairs'), ('SENTENCE_ORDER', 'Sentence Order'), ('TRUE_FALSE', 'True/False Questions'), ('LISTENING', 'Listening Comprehension'), ('SPEAKING', 'Speaking Practice'), ('VAPI_CONVERSATION', 'AI Conversation Practice')], help_text='Type of challenge exercise', max_length=25),
        ),
    ]
