# Generated by Django 4.2.24 on 2026-02-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_add_listening_speaking_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicechallenge',
            name='reference_audio_url',
            field=models.URLField(blank=True, help_text='URL of the reference audio for pronunciation practice (TTS generated)', null=True),
        ),
    ]
