# Generated by Django 5.2.5 on 2025-08-18 12:54

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's email address - used for login", max_length=254, unique=True)),
                ('name', models.CharField(help_text="User's full name", max_length=255)),
                ('phone', models.CharField(blank=True, help_text="User's phone number", max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('avatar', models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='avatars/%Y/%m/')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('braider', 'Braider'), ('admin', 'Administrator')], default='customer', help_text="User's role in the system", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.')),
                ('email_verified', models.BooleanField(default=False, help_text="Whether the user's email has been verified")),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=255)),
                ('reset_password_token', models.CharField(blank=True, help_text='Token for password reset', max_length=255)),
                ('reset_password_expires', models.DateTimeField(blank=True, help_text='When the password reset token expires', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences and settings')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='tuwi_users', related_query_name='tuwi_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='tuwi_users', related_query_name='tuwi_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('email_bookings', models.BooleanField(default=True, help_text='Receive email notifications for booking updates')),
                ('email_messages', models.BooleanField(default=True, help_text='Receive email notifications for new messages')),
                ('email_ratings', models.BooleanField(default=True, help_text='Receive email notifications for new ratings')),
                ('email_orders', models.BooleanField(default=True, help_text='Receive email notifications for order updates')),
                ('email_marketing', models.BooleanField(default=False, help_text='Receive marketing emails')),
                ('push_bookings', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_ratings', models.BooleanField(default=True)),
                ('push_orders', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='daily', help_text='How often to receive digest emails', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('timezone', models.CharField(default='Europe/Lisbon', help_text="User's timezone for notification timing", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('address_type', models.CharField(choices=[('billing', 'Billing Address'), ('shipping', 'Shipping Address'), ('home', 'Home Address'), ('work', 'Work Address')], default='home', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default address for this type")),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'db_table': 'user_addresses',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified'], name='users_email_v_0e5f70_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'address_type'], name='user_addres_user_id_8ff364_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['is_default'], name='user_addres_is_defa_43d9e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('user', 'address_type', 'is_default')},
        ),
    ]
