# Generated by Django 4.2.23 on 2025-08-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True,
                help_text="Google OAuth user ID",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
