# Generated by Django 4.2.23 on 2025-08-20 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_google_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit verification code", max_length=6
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address this verification is for",
                        max_length=254,
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this verification code has been used",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this verification code expires"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of verification attempts"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum number of attempts allowed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "db_table": "email_verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="email_verif_user_id_d1db3b_idx"
                    ),
                    models.Index(fields=["email"], name="email_verif_email_66a8a7_idx"),
                    models.Index(fields=["code"], name="email_verif_code_2d0f52_idx"),
                    models.Index(
                        fields=["expires_at"], name="email_verif_expires_fdd67c_idx"
                    ),
                    models.Index(
                        fields=["is_used"], name="email_verif_is_used_1f597c_idx"
                    ),
                ],
            },
        ),
    ]
