# Generated by Django 4.2.24 on 2025-09-13 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_update_user_roles_for_proenglish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de telefone no formato internacional (ex: +244912345678 para Angola)', max_length=20, validators=[django.core.validators.RegexValidator(message="Número de telefone deve estar no formato internacional: '+244912345678' (Angola) ou '+351912345678' (Portugal).", regex='^\\+(?:[1-9]\\d{0,3})?[1-9]\\d{8,14}$')]),
        ),
    ]
