# Generated by Django 4.2.24 on 2026-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_allow_phone_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['user', 'address_type', '-is_default', 'created_at'], 'verbose_name': 'User Address', 'verbose_name_plural': 'User Addresses'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text="User's profile picture URL (S3/CloudFront)", max_length=500, null=True),
        ),
    ]
