# Generated by Django 4.2.24 on 2026-02-26 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_change_avatar_to_urlfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('lesson', 'Lesson Feedback'), ('ai_tutor', 'AI Tutor Feedback'), ('content', 'Content Quality'), ('testimonial', 'Testimonial')], default='general', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5', null=True)),
                ('nps_score', models.PositiveSmallIntegerField(blank=True, help_text='Net Promoter Score (0-10)', null=True)),
                ('comment', models.TextField(blank=True, help_text="User's feedback comment")),
                ('trigger', models.CharField(choices=[('first_lesson', 'After First Lesson'), ('milestone_lessons', 'Milestone Lessons Completed'), ('course_complete', 'Course Completed'), ('ai_sessions', 'AI Tutor Sessions'), ('days_active', 'Days Active'), ('manual', 'User Initiated'), ('prompt', 'System Prompt')], default='manual', help_text='What triggered this feedback request', max_length=30)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context (lessons completed, course, etc.)')),
                ('allow_public', models.BooleanField(default=False, help_text='User allows this feedback to be used as testimonial')),
                ('allow_contact', models.BooleanField(default=False, help_text='User allows follow-up contact')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Whether admin has reviewed this feedback')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'db_table': 'user_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEngagementMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('total_lessons_completed', models.PositiveIntegerField(default=0)),
                ('total_courses_completed', models.PositiveIntegerField(default=0)),
                ('total_ai_sessions', models.PositiveIntegerField(default=0)),
                ('total_ai_minutes', models.PositiveIntegerField(default=0)),
                ('total_days_active', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_feedbacks_given', models.PositiveIntegerField(default=0)),
                ('last_feedback_at', models.DateTimeField(blank=True, null=True)),
                ('last_prompt_at', models.DateTimeField(blank=True, null=True)),
                ('first_lesson_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Engagement Metrics',
                'verbose_name_plural': 'User Engagement Metrics',
                'db_table': 'user_engagement_metrics',
            },
        ),
        migrations.CreateModel(
            name='FeedbackPromptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('trigger', models.CharField(help_text='What triggered this prompt', max_length=30)),
                ('status', models.CharField(choices=[('shown', 'Prompt Shown'), ('dismissed', 'User Dismissed'), ('completed', 'Feedback Completed'), ('skipped', 'User Skipped')], default='shown', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context when prompt was shown (lessons count, etc.)')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_logs', to='users.userfeedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_prompt_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Prompt Log',
                'verbose_name_plural': 'Feedback Prompt Logs',
                'db_table': 'feedback_prompt_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['user'], name='user_feedba_user_id_976445_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['feedback_type'], name='user_feedba_feedbac_519e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['rating'], name='user_feedba_rating_848624_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['trigger'], name='user_feedba_trigger_26e091_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['allow_public'], name='user_feedba_allow_p_4a7df6_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['is_reviewed'], name='user_feedba_is_revi_a5fefe_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['created_at'], name='user_feedba_created_f75066_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementmetrics',
            index=models.Index(fields=['total_lessons_completed'], name='user_engage_total_l_e4e5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementmetrics',
            index=models.Index(fields=['total_ai_sessions'], name='user_engage_total_a_ab1584_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementmetrics',
            index=models.Index(fields=['total_days_active'], name='user_engage_total_d_e73b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementmetrics',
            index=models.Index(fields=['last_feedback_at'], name='user_engage_last_fe_256ece_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementmetrics',
            index=models.Index(fields=['last_prompt_at'], name='user_engage_last_pr_2bf841_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackpromptlog',
            index=models.Index(fields=['user'], name='feedback_pr_user_id_ee74b4_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackpromptlog',
            index=models.Index(fields=['trigger'], name='feedback_pr_trigger_5a63bc_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackpromptlog',
            index=models.Index(fields=['status'], name='feedback_pr_status_cbdaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackpromptlog',
            index=models.Index(fields=['created_at'], name='feedback_pr_created_d12e7a_idx'),
        ),
    ]
