# Generated by Django 5.2.5 on 2025-08-18 13:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('braiders', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('booking_date', models.DateField(help_text='Date of the appointment')),
                ('booking_time', models.TimeField(help_text='Start time of the appointment')),
                ('estimated_end_time', models.TimeField(blank=True, help_text='Estimated end time (calculated from service duration)', null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='Actual start time of service', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='Actual end time of service', null=True)),
                ('booking_type', models.CharField(choices=[('home', 'Home Service (Domicílio)'), ('salon', 'Salon Service (Estabelecimento)')], help_text='Type of booking (home or salon service)', max_length=20)),
                ('client_name', models.CharField(help_text="Client's full name", max_length=255)),
                ('client_phone', models.CharField(help_text="Client's contact phone", max_length=20)),
                ('client_email', models.EmailField(help_text="Client's contact email", max_length=254)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests from the client')),
                ('hair_type', models.CharField(blank=True, help_text="Client's hair type (e.g., 4C)", max_length=10)),
                ('hair_length', models.CharField(blank=True, help_text="Client's current hair length", max_length=50)),
                ('preferred_products', models.JSONField(blank=True, default=list, help_text="Client's preferred products or allergies")),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base service price at booking time', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('additional_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional charges (travel, materials, etc.)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the booking', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('deposit_paid', 'Deposit Paid'), ('paid', 'Fully Paid'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('cancelled', 'Payment Cancelled')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=50)),
                ('payment_intent_id', models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=255)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Deposit amount (if applicable)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled_client', 'Cancelled by Client'), ('cancelled_braider', 'Cancelled by Braider'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', help_text='Booking status', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the booking was confirmed', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the booking was cancelled', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the service was completed', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Notes about service completion')),
                ('booking_reference', models.CharField(blank=True, help_text='Unique booking reference for clients', max_length=20, unique=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for admin/braider')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder was sent to client')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='When reminder was sent', null=True)),
                ('braider', models.ForeignKey(help_text='Braider providing the service', on_delete=django.db.models.deletion.CASCADE, related_name='received_bookings', to='braiders.braider')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Who cancelled the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Who confirmed the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='braiders.service')),
                ('service_address', models.ForeignKey(blank=True, help_text='Address for home service (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.address')),
                ('user', models.ForeignKey(help_text='Client who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('old_status', models.CharField(blank=True, help_text='Previous status', max_length=20)),
                ('new_status', models.CharField(help_text='New status', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('automatic', models.BooleanField(default=False, help_text='Whether change was automatic')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Status History',
                'verbose_name_plural': 'Booking Status History',
                'db_table': 'booking_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('date', models.DateField(help_text='Date for this exception')),
                ('exception_type', models.CharField(choices=[('unavailable', 'Unavailable'), ('limited', 'Limited Hours'), ('special', 'Special Hours')], help_text='Type of exception', max_length=20)),
                ('start_time', models.TimeField(blank=True, help_text='Special start time (for limited/special hours)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Special end time (for limited/special hours)', null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for exception (holiday, personal, etc.)', max_length=200)),
                ('braider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='braiders.braider')),
            ],
            options={
                'verbose_name': 'Availability Exception',
                'verbose_name_plural': 'Availability Exceptions',
                'db_table': 'availability_exceptions',
                'indexes': [models.Index(fields=['braider', 'date'], name='availabilit_braider_21b255_idx'), models.Index(fields=['exception_type'], name='availabilit_excepti_28fbf5_idx')],
                'unique_together': {('braider', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('start_date', models.DateField(help_text='Start date for this availability pattern')),
                ('end_date', models.DateField(blank=True, help_text='End date (null for indefinite)', null=True)),
                ('start_time', models.TimeField(help_text='Start time for availability')),
                ('end_time', models.TimeField(help_text='End time for availability')),
                ('recurrence_type', models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often this availability repeats', max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Days of week (0=Monday, 6=Sunday) for weekly recurrence')),
                ('is_home_service', models.BooleanField(default=True, help_text='Whether this slot is for home service')),
                ('is_salon_service', models.BooleanField(default=False, help_text='Whether this slot is for salon service')),
                ('min_advance_hours', models.PositiveIntegerField(default=24, help_text='Minimum hours in advance for booking')),
                ('max_advance_days', models.PositiveIntegerField(default=90, help_text='Maximum days in advance for booking')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this availability slot is active')),
                ('braider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='braiders.braider')),
            ],
            options={
                'verbose_name': 'Availability Slot',
                'verbose_name_plural': 'Availability Slots',
                'db_table': 'availability_slots',
                'indexes': [models.Index(fields=['braider', 'start_date', 'end_date'], name='availabilit_braider_6f08fb_idx'), models.Index(fields=['is_active'], name='availabilit_is_acti_264bd7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booking_date'], name='bookings_user_id_5183db_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['braider', 'booking_date'], name='bookings_braider_0209f0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'booking_date'], name='bookings_service_bf06c1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'booking_time'], name='bookings_booking_a7d490_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='bookings_payment_3ea9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_booking_4d53ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'in_progress'])), fields=('braider', 'booking_date', 'booking_time'), name='unique_braider_booking_slot'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['booking', 'created_at'], name='booking_sta_booking_96150c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['new_status'], name='booking_sta_new_sta_8f7320_idx'),
        ),
    ]
