# Generated by Django 5.2.5 on 2025-08-18 23:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('percentage', 'Percentage'), ('currency', 'Currency'), ('duration', 'Duration')], default='counter', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (€, %, s, etc.)', max_length=20)),
                ('aggregation_type', models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('count', 'Count'), ('min', 'Minimum'), ('max', 'Maximum'), ('last', 'Last Value')], default='sum', max_length=20)),
                ('calculation_query', models.TextField(blank=True, help_text='SQL query or calculation logic')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on main dashboard')),
                ('is_active', models.BooleanField(default=True)),
                ('format_string', models.CharField(default='{value}', help_text='Format template for display', max_length=50)),
                ('has_alerts', models.BooleanField(default=False)),
                ('alert_threshold_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('alert_threshold_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetricCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Metric Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CohortAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('cohort_period', models.DateField(help_text='Period when cohort was created')),
                ('analysis_period', models.DateField(help_text='Period being analyzed')),
                ('cohort_size', models.PositiveIntegerField(help_text='Total users in cohort')),
                ('active_users', models.PositiveIntegerField(help_text='Active users in analysis period')),
                ('retention_rate', models.DecimalField(decimal_places=2, help_text='Retention rate percentage', max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_revenue_per_user', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_bookings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('period_number', models.PositiveIntegerField(help_text='Period number since cohort creation')),
            ],
            options={
                'ordering': ['cohort_period', 'period_number'],
                'indexes': [models.Index(fields=['cohort_period'], name='analytics_c_cohort__a2483b_idx'), models.Index(fields=['analysis_period'], name='analytics_c_analysi_44ec07_idx')],
                'unique_together': {('cohort_period', 'analysis_period')},
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('dashboard_type', models.CharField(choices=[('executive', 'Executive Dashboard'), ('operational', 'Operational Dashboard'), ('financial', 'Financial Dashboard'), ('user_behavior', 'User Behavior Dashboard'), ('braider_performance', 'Braider Performance Dashboard'), ('custom', 'Custom Dashboard')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of allowed user roles')),
                ('layout_config', models.JSONField(default=dict, help_text='Dashboard layout configuration')),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='Auto-refresh interval in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='custom_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('title', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('metric_card', 'Metric Card'), ('chart_line', 'Line Chart'), ('chart_bar', 'Bar Chart'), ('chart_pie', 'Pie Chart'), ('chart_area', 'Area Chart'), ('table', 'Data Table'), ('heatmap', 'Heatmap'), ('gauge', 'Gauge'), ('progress', 'Progress Bar'), ('list', 'List')], max_length=20)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=6)),
                ('height', models.PositiveIntegerField(default=4)),
                ('data_query', models.TextField(blank=True, help_text='Custom data query if needed')),
                ('filters', models.JSONField(default=dict, help_text='Filters to apply to data')),
                ('chart_config', models.JSONField(default=dict, help_text='Chart.js configuration')),
                ('refresh_interval', models.PositiveIntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard')),
                ('metrics', models.ManyToManyField(related_name='widgets', to='analytics.businessmetric')),
            ],
            options={
                'ordering': ['dashboard', 'position_y', 'position_x'],
            },
        ),
        migrations.AddField(
            model_name='businessmetric',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.metriccategory'),
        ),
        migrations.CreateModel(
            name='MetricDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dimensions', models.JSONField(default=dict, help_text='Additional dimensions for filtering')),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('day_of_week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('week', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='analytics.businessmetric')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('yearly', 'Yearly Report'), ('custom', 'Custom Report')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(default=dict)),
                ('schedule_type', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='manual', max_length=20)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('schedule_day_of_week', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule_day_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('email_recipients', models.JSONField(default=list, help_text='Email addresses to send report')),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.ManyToManyField(related_name='reports', to='analytics.businessmetric')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='analytics.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('performance_type', models.CharField(choices=[('response_time', 'Response Time'), ('error_rate', 'Error Rate'), ('throughput', 'Throughput'), ('cpu_usage', 'CPU Usage'), ('memory_usage', 'Memory Usage'), ('db_performance', 'Database Performance'), ('cache_hit_rate', 'Cache Hit Rate')], max_length=30)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['performance_type', '-timestamp'], name='analytics_s_perform_d70f2c_idx'), models.Index(fields=['timestamp'], name='analytics_s_timesta_5ef962_idx'), models.Index(fields=['endpoint', '-timestamp'], name='analytics_s_endpoin_0b41d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('booking_created', 'Booking Created'), ('booking_cancelled', 'Booking Cancelled'), ('payment_made', 'Payment Made'), ('profile_updated', 'Profile Updated'), ('search_performed', 'Search Performed'), ('page_view', 'Page View'), ('feature_used', 'Feature Used'), ('error_occurred', 'Error Occurred')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(default=dict, help_text='Additional activity data')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('title', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('metric_threshold', 'Metric Threshold'), ('system_error', 'System Error'), ('performance_issue', 'Performance Issue'), ('business_anomaly', 'Business Anomaly'), ('security_concern', 'Security Concern')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('triggered_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='active', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_channels', models.JSONField(default=list, help_text='Channels where notification was sent')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.businessmetric')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='analytics_a_status_39105a_idx'), models.Index(fields=['severity', '-created_at'], name='analytics_a_severit_b7e760_idx'), models.Index(fields=['alert_type'], name='analytics_a_alert_t_58746a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['dashboard_type', 'is_active'], name='analytics_d_dashboa_e11e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['dashboard', 'is_active'], name='analytics_d_dashboa_0bf48e_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetric',
            index=models.Index(fields=['category', 'is_active'], name='analytics_b_categor_542a94_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetric',
            index=models.Index(fields=['is_featured'], name='analytics_b_is_feat_351bba_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdatapoint',
            index=models.Index(fields=['metric', '-timestamp'], name='analytics_m_metric__60fc39_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdatapoint',
            index=models.Index(fields=['metric', 'date'], name='analytics_m_metric__39ae54_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdatapoint',
            index=models.Index(fields=['date'], name='analytics_m_date_bce2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='metricdatapoint',
            index=models.Index(fields=['year', 'month'], name='analytics_m_year_95093d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metricdatapoint',
            unique_together={('metric', 'timestamp', 'dimensions')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'is_active'], name='analytics_r_report__51f9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['next_scheduled'], name='analytics_r_next_sc_13780a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportgeneration',
            index=models.Index(fields=['report', '-created_at'], name='analytics_r_report__d20119_idx'),
        ),
        migrations.AddIndex(
            model_name='reportgeneration',
            index=models.Index(fields=['status'], name='analytics_r_status_8ca19a_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_779c80_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type', '-timestamp'], name='analytics_u_activit_7a754e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='analytics_u_timesta_2b8b17_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_id'], name='analytics_u_session_0e759b_idx'),
        ),
    ]
