# Generated by Django 4.2.24 on 2025-09-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='service_type',
            field=models.CharField(choices=[('course', 'Curso Especializado'), ('practice_lab', 'Practice Lab'), ('ai_tutor', 'IA Personal Tutor'), ('other', 'Outros')], default='course', max_length=20),
        ),
    ]
