# Generated by Django 5.2.5 on 2025-08-18 23:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('model_type', models.CharField(choices=[('recommendation', 'Recommendation Engine'), ('sentiment', 'Sentiment Analysis'), ('fraud_detection', 'Fraud Detection'), ('demand_forecasting', 'Demand Forecasting'), ('price_optimization', 'Price Optimization'), ('churn_prediction', 'Churn Prediction'), ('clustering', 'User Clustering'), ('chatbot', 'Chatbot NLP'), ('personalization', 'Content Personalization')], max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('algorithm', models.CharField(blank=True, max_length=100)),
                ('features', models.JSONField(default=list, help_text='List of features used')),
                ('hyperparameters', models.JSONField(default=dict, help_text='Model hyperparameters')),
                ('model_data', models.TextField(blank=True, help_text='Serialized model')),
                ('accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('precision', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('recall', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('f1_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('training_data_size', models.PositiveIntegerField(blank=True, null=True)),
                ('training_started', models.DateTimeField(blank=True, null=True)),
                ('training_completed', models.DateTimeField(blank=True, null=True)),
                ('training_duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('training', 'Training'), ('active', 'Active'), ('inactive', 'Inactive'), ('deprecated', 'Deprecated'), ('failed', 'Failed')], default='training', max_length=20)),
                ('is_production', models.BooleanField(default=False)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('prediction_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'status'], name='ml_mlmodel_model_t_4ee29f_idx'), models.Index(fields=['status', 'is_production'], name='ml_mlmodel_status_7a2e84_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('churn_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=10)),
                ('churn_factors', models.JSONField(default=list, help_text='Factors contributing to churn risk')),
                ('feature_importance', models.JSONField(default=dict, help_text='Feature importance scores')),
                ('retention_actions', models.JSONField(default=list, help_text='Recommended retention actions')),
                ('actual_churned', models.BooleanField(blank=True, null=True)),
                ('retention_action_taken', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to='ml.mlmodel')),
            ],
            options={
                'ordering': ['-churn_probability'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ml_churnpre_user_id_716261_idx'), models.Index(fields=['risk_level', '-churn_probability'], name='ml_churnpre_risk_le_7cbec3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('content_type', models.CharField(choices=[('review', 'User Review'), ('comment', 'Comment'), ('message', 'Chat Message'), ('feedback', 'Feedback'), ('social_post', 'Social Media Post')], max_length=20)),
                ('content_id', models.CharField(help_text='ID of analyzed content', max_length=100)),
                ('text_content', models.TextField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('positive_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('negative_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('neutral_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('keywords', models.JSONField(default=list, help_text='Key phrases extracted')),
                ('emotions', models.JSONField(default=dict, help_text='Emotion detection results')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analyses', to='ml.mlmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'sentiment'], name='ml_sentimen_content_33bdad_idx'), models.Index(fields=['user', '-created_at'], name='ml_sentimen_user_id_a6f19d_idx'), models.Index(fields=['sentiment', '-confidence_score'], name='ml_sentimen_sentime_7139e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('recommendation_type', models.CharField(choices=[('braider', 'Braider Recommendation'), ('service', 'Service Recommendation'), ('product', 'Product Recommendation'), ('content', 'Content Recommendation')], max_length=20)),
                ('item_id', models.CharField(help_text='ID of recommended item', max_length=100)),
                ('item_type', models.CharField(help_text='Type of recommended item', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('relevance_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('recommendation_context', models.JSONField(default=dict, help_text='Context that generated recommendation')),
                ('features_used', models.JSONField(default=list, help_text='Features used for this recommendation')),
                ('viewed', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('converted', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ml.mlmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'recommendation_type'], name='ml_userreco_user_id_e07630_idx'), models.Index(fields=['user', '-confidence_score'], name='ml_userreco_user_id_3ce93c_idx'), models.Index(fields=['item_id', 'item_type'], name='ml_userreco_item_id_4a1c35_idx')],
            },
        ),
    ]
