# Generated by Django 5.2.5 on 2025-08-18 13:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Braider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(help_text='Professional name or business name', max_length=255)),
                ('contact_email', models.EmailField(help_text='Primary contact email for bookings', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Professional bio and description')),
                ('service_areas', models.JSONField(blank=True, default=list, help_text='List of areas where braider provides services')),
                ('provides_home_service', models.BooleanField(default=True, help_text="Whether braider goes to client's location")),
                ('has_physical_location', models.BooleanField(default=False, help_text='Whether braider has a physical salon/studio')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='braiders/profiles/%Y/%m/')),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Years of professional experience', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner (0-2 years)'), ('intermediate', 'Intermediate (2-5 years)'), ('advanced', 'Advanced (5-10 years)'), ('expert', 'Expert (10+ years)')], help_text='Professional experience level', max_length=20)),
                ('specialties', models.JSONField(blank=True, default=list, help_text="List of specialties (e.g., 'Box Braids', 'Senegalese Twists')")),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Professional certifications and courses')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', help_text='Approval status', max_length=20)),
                ('status_reason', models.TextField(blank=True, help_text='Reason for rejection or suspension')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the braider was approved', null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average rating from reviews', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0, help_text='Total number of reviews')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether braider is featured on homepage')),
                ('featured_until', models.DateTimeField(blank=True, help_text='When featured status expires', null=True)),
                ('availability_schedule', models.JSONField(blank=True, default=dict, help_text='Weekly availability schedule')),
                ('pricing_info', models.JSONField(blank=True, default=dict, help_text='Base pricing information and policies')),
                ('booking_advance_days', models.PositiveIntegerField(default=1, help_text='Minimum days in advance for booking')),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation and refund policy')),
                ('instagram_handle', models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('website_url', models.URLField(blank=True, help_text='Personal website or portfolio')),
                ('address', models.ForeignKey(blank=True, help_text='Primary business address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='braiders', to='core.address')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this braider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_braiders', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='braider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Braider',
                'verbose_name_plural': 'Braiders',
                'db_table': 'braiders',
            },
        ),
        migrations.CreateModel(
            name='BraiderPortfolioImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('image', models.ImageField(help_text='Portfolio image', upload_to='braiders/portfolio/%Y/%m/')),
                ('title', models.CharField(blank=True, help_text='Image title or description', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the work')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing the image')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this image should be featured in profile')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in portfolio')),
                ('braider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='braiders.braider')),
            ],
            options={
                'verbose_name': 'Portfolio Image',
                'verbose_name_plural': 'Portfolio Images',
                'db_table': 'braider_portfolio_images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(help_text='Service name', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings', max_length=500)),
                ('category', models.CharField(choices=[('braids', 'Tranças'), ('twists', 'Twists'), ('locs', 'Locs/Dreadlocks'), ('protective', 'Penteados Protetores'), ('natural_care', 'Cuidados Naturais'), ('styling', 'Penteados e Styling'), ('maintenance', 'Manutenção'), ('consultation', 'Consultoria')], help_text='Service category', max_length=20)),
                ('subcategory', models.CharField(blank=True, help_text='Specific subcategory or style', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Additional tags for search and filtering')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for the service', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_varies', models.BooleanField(default=False, help_text='Whether price varies based on factors (length, complexity, etc.)')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price (when price varies)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price (when price varies)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_factors', models.JSONField(blank=True, default=list, help_text='Factors that affect pricing (e.g., hair length, extensions needed)')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Estimated duration in minutes', validators=[django.core.validators.MinValueValidator(15)])),
                ('duration_varies', models.BooleanField(default=False, help_text='Whether duration varies')),
                ('min_duration', models.PositiveIntegerField(blank=True, help_text='Minimum duration when varies', null=True)),
                ('max_duration', models.PositiveIntegerField(blank=True, help_text='Maximum duration when varies', null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('expert', 'Especialista')], help_text='Difficulty level of the service', max_length=20)),
                ('hair_type_compatibility', models.JSONField(blank=True, default=list, help_text='Compatible hair types')),
                ('required_hair_length', models.CharField(blank=True, help_text='Minimum hair length required', max_length=100)),
                ('client_preparation', models.TextField(blank=True, help_text='What client needs to do before appointment')),
                ('braider_provides', models.JSONField(blank=True, default=list, help_text='Materials/products provided by braider')),
                ('client_brings', models.JSONField(blank=True, default=list, help_text='Materials client needs to bring')),
                ('aftercare_instructions', models.TextField(blank=True, help_text='How to care for the style')),
                ('maintenance_schedule', models.CharField(blank=True, help_text='Recommended maintenance schedule', max_length=200)),
                ('style_duration', models.CharField(blank=True, help_text='How long the style typically lasts', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Main service image', null=True, upload_to='services/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether service is currently offered')),
                ('is_popular', models.BooleanField(default=False, help_text='Whether service should be highlighted as popular')),
                ('braider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='braiders.braider')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('image', models.ImageField(help_text='Service image', upload_to='services/gallery/%Y/%m/')),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('process', 'Process'), ('detail', 'Detail'), ('styling', 'Styling Option')], default='after', help_text='Type of image', max_length=20)),
                ('caption', models.CharField(blank=True, help_text='Image caption or description', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='braiders.service')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
                'db_table': 'service_images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='braider',
            index=models.Index(fields=['status'], name='braiders_status_347d28_idx'),
        ),
        migrations.AddIndex(
            model_name='braider',
            index=models.Index(fields=['is_featured'], name='braiders_is_feat_d95a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='braider',
            index=models.Index(fields=['average_rating'], name='braiders_average_fc9ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='braider',
            index=models.Index(fields=['created_at'], name='braiders_created_51dd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='braider',
            index=models.Index(fields=['approved_at'], name='braiders_approve_70e9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='braiderportfolioimage',
            index=models.Index(fields=['braider', 'is_featured'], name='braider_por_braider_37cdc7_idx'),
        ),
        migrations.AddIndex(
            model_name='braiderportfolioimage',
            index=models.Index(fields=['order'], name='braider_por_order_35ebd7_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['braider', 'is_active'], name='services_braider_30cae1_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='services_categor_54c742_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['base_price'], name='services_base_pr_395222_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_popular'], name='services_is_popu_a06b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='services_created_22da02_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['service', 'image_type'], name='service_ima_service_27c950_idx'),
        ),
    ]
