# Generated by Django 5.2.5 on 2025-08-18 18:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braiders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='braider',
            name='communication_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average communication rating', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='braider',
            name='professionalism_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average professionalism rating', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='braider',
            name='quality_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average quality rating', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='braider',
            name='value_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average value for money rating', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
