# Generated by Django 5.2.5 on 2025-08-18 18:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('priority', models.IntegerField(default=1, help_text='Higher numbers = higher priority')),
                ('is_system', models.BooleanField(default=False, help_text='System notifications cannot be disabled')),
            ],
            options={
                'verbose_name_plural': 'Notification Categories',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['priority'], name='notificatio_priorit_b4aa2d_idx'), models.Index(fields=['is_system'], name='notificatio_is_syst_504592_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS'), ('in_app', 'In-App'), ('webhook', 'Webhook')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text='Channel-specific configuration (API keys, URLs, etc.)')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000)),
                ('rate_limit_per_day', models.PositiveIntegerField(default=10000)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['channel_type'], name='notificatio_channel_e00152_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_06813e_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(help_text='Unique template name', max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS'), ('in_app', 'In-App Notification')], max_length=20)),
                ('subject_template', models.CharField(help_text='Subject line template', max_length=200)),
                ('body_template', models.TextField(help_text='Message body template with variables')),
                ('html_template', models.TextField(blank=True, help_text='HTML template for rich content')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('variables', models.JSONField(default=dict, help_text='Available template variables and their descriptions')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['template_type'], name='notificatio_templat_5e0a58_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_b2a982_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict, help_text='Additional data for rich notifications')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to send notification (null = send immediately)', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('external_id', models.CharField(blank=True, help_text='External provider ID', max_length=200)),
                ('provider_response', models.JSONField(default=dict, help_text='Response from notification provider')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationcategory')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationchannel')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('marketing_enabled', models.BooleanField(default=True)),
                ('promotional_enabled', models.BooleanField(default=True)),
                ('system_enabled', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='daily', max_length=20)),
                ('category_preferences', models.JSONField(default=dict, help_text='Preferences by notification category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('opens', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('time_to_read', models.DurationField(blank=True, null=True)),
                ('time_to_click', models.DurationField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='notifications.notification')),
            ],
            options={
                'verbose_name_plural': 'Notification Analytics',
                'indexes': [models.Index(fields=['notification'], name='notificatio_notific_1ae201_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('context_data', models.JSONField(default=dict, help_text='Common context for all notifications')),
                ('recipient_data', models.JSONField(default=list, help_text='Individual recipient data')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationcategory')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_processed'], name='notificatio_is_proc_00544a_idx'), models.Index(fields=['scheduled_at'], name='notificatio_schedul_25d178_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_a9c93f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category'], name='notificatio_categor_a0f58b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_265656_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['external_id'], name='notificatio_externa_33ff6b_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationpreference',
            index=models.Index(fields=['user'], name='notificatio_user_id_e117a5_idx'),
        ),
    ]
