# Generated by Django 5.2.5 on 2025-08-19 06:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('is_typing', models.BooleanField(default=True, help_text='Whether user is currently typing')),
                ('started_typing_at', models.DateTimeField(auto_now_add=True, help_text='When user started typing')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last typing activity (updated on each keystroke)')),
                ('typing_context', models.JSONField(blank=True, default=dict, help_text='Additional context about what user is typing (draft message length, etc.)')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'is_typing'], name='chat_typing_convers_302801_idx'), models.Index(fields=['user', 'is_typing'], name='chat_typing_user_id_02ad05_idx'), models.Index(fields=['last_activity'], name='chat_typing_last_ac_2a496e_idx')],
                'unique_together': {('conversation', 'user')},
            },
        ),
    ]
